import type { BackoffParams } from "../value-objects/backoff.vo.js";
import type { JobPriority, JobVO } from "../value-objects/job.vo.js";

export const JOB_REPOSITORY = Symbol("IJobRepository");

export interface SubmitJobInput {
    id: string; // UUIDv7, generated by the handler
    type: string;
    payload: Record<string, unknown>;
    priority: JobPriority;
    runAt: Date;
    maxAttempts: number;
    idempotencyKey?: string;
}

export interface ClaimJobsInput {
    workerId: string;
    capabilities: string[];
    batchSize: number;
    leaseSeconds: number;
}

export interface FailJobInput {
    jobId: string;
    workerId: string;
    error: string;
    backoff: BackoffParams;
}

export interface IJobRepository {
    /**
     * Insert a new job. If `idempotencyKey` is set and already belongs to an
     * existing job, that existing job is returned unchanged instead of
     * inserting a duplicate — submission-time idempotency (see docs/semantics).
     */
    submit(input: SubmitJobInput): Promise<JobVO>;

    /** Fetch a job by id, or `null` if it does not exist. */
    findById(id: string): Promise<JobVO | null>;

    /**
     * Claim up to `batchSize` QUEUED jobs that are due (`run_at <= now`) and
     * whose `type` is in `capabilities`, ordered by priority desc then
     * run_at asc, marking each PROCESSING with a lease of `leaseSeconds` and
     * incrementing `attempts`. Uses SELECT ... FOR UPDATE SKIP LOCKED, so
     * concurrent claims never block each other and never hand out the same
     * job twice.
     */
    claim(input: ClaimJobsInput): Promise<JobVO[]>;

    /**
     * Mark a PROCESSING job COMPLETED and store `result`. Guarded: applies
     * only while the job is still PROCESSING and still leased by `workerId`
     * (a worker whose lease expired and was reclaimed must not be able to
     * ack). Throws AppError.conflict if the guard fails.
     */
    ack(
        jobId: string,
        workerId: string,
        result: Record<string, unknown> | null,
    ): Promise<JobVO>;

    /**
     * Report a PROCESSING job as failed (same lease guard as `ack`). Moves it
     * to DEAD_LETTER when `attempts >= maxAttempts`, otherwise back to QUEUED
     * with `run_at` pushed out by an exponential backoff.
     */
    fail(input: FailJobInput): Promise<JobVO>;

    /**
     * Extend a PROCESSING job's lease by `leaseSeconds` (same guard as `ack`).
     * A worker running a handler longer than the lease calls this to keep the
     * recovery loop from reclaiming a job that's still being worked.
     */
    renewLease(
        jobId: string,
        workerId: string,
        leaseSeconds: number,
    ): Promise<JobVO>;

    /**
     * Requeue every PROCESSING job held by a worker in `deadWorkerIds` —
     * status back to QUEUED, lock and lease cleared. Returns the count.
     */
    reclaimFromDeadWorkers(deadWorkerIds: string[]): Promise<number>;

    /**
     * The safety net: requeue any PROCESSING job whose `lease_expires_at` is
     * in the past, regardless of its worker's heartbeat status. Returns the
     * count. Runs alongside reclaimFromDeadWorkers — see JobRecoveryScheduler
     * for why both exist.
     */
    reclaimExpiredLeases(): Promise<number>;
}
