import type { BackoffParams } from "../value-objects/backoff.vo.js";
import type { JobPriority, JobVO } from "../value-objects/job.vo.js";

export const JOB_REPOSITORY = Symbol("IJobRepository");

export interface SubmitJobInput {
    id: string; // UUIDv7, generated by the handler
    type: string;
    payload: Record<string, unknown>;
    priority: JobPriority;
    runAt: Date;
    maxAttempts: number;
    idempotencyKey?: string;
}

export interface ClaimJobsInput {
    workerId: string;
    capabilities: string[];
    batchSize: number;
    leaseSeconds: number;
    /**
     * Fleet-wide cap on simultaneous PROCESSING jobs, per type — counted
     * across every worker, not just this one. Types not present here are
     * unrestricted.
     */
    typeConcurrencyLimits: Record<string, number>;
}

export interface FailJobInput {
    jobId: string;
    workerId: string;
    error: string;
    backoff: BackoffParams;
}

export interface ListDeadLetterJobsInput {
    limit: number;
    offset: number;
}

export interface ListDeadLetterJobsResult {
    jobs: JobVO[];
    total: number;
}

export interface IJobRepository {
    /**
     * Insert a new job. If `idempotencyKey` is set and already belongs to an
     * existing job, that existing job is returned unchanged instead of
     * inserting a duplicate — submission-time idempotency (see docs/semantics).
     */
    submit(input: SubmitJobInput): Promise<JobVO>;

    /** Fetch a job by id, or `null` if it does not exist. */
    findById(id: string): Promise<JobVO | null>;

    /**
     * Claim up to `batchSize` QUEUED jobs that are due (`run_at <= now`) and
     * whose `type` is in `capabilities`, ordered by priority desc then
     * run_at asc, marking each PROCESSING with a lease of `leaseSeconds` and
     * incrementing `attempts`. Uses SELECT ... FOR UPDATE SKIP LOCKED, so
     * concurrent claims never block each other and never hand out the same
     * job twice. A type present in `typeConcurrencyLimits` is further capped
     * so the number already PROCESSING plus what this call claims never
     * exceeds the limit, fleet-wide — which can mean this returns fewer
     * than `batchSize` jobs even when more are QUEUED and due, rather than
     * widening the locked scan to backfill (that would let one claim call
     * lock far more rows than it uses, starving concurrent claimers).
     */
    claim(input: ClaimJobsInput): Promise<JobVO[]>;

    /**
     * Mark a PROCESSING job COMPLETED and store `result`. Guarded: applies
     * only while the job is still PROCESSING and still leased by `workerId`
     * (a worker whose lease expired and was reclaimed must not be able to
     * ack). Throws AppError.conflict if the guard fails.
     */
    ack(
        jobId: string,
        workerId: string,
        result: Record<string, unknown> | null,
    ): Promise<JobVO>;

    /**
     * Report a PROCESSING job as failed (same lease guard as `ack`). Moves it
     * to DEAD_LETTER when `attempts >= maxAttempts`, otherwise back to QUEUED
     * with `run_at` pushed out by an exponential backoff.
     */
    fail(input: FailJobInput): Promise<JobVO>;

    /**
     * Extend a PROCESSING job's lease by `leaseSeconds` (same guard as `ack`).
     * A worker running a handler longer than the lease calls this to keep the
     * recovery loop from reclaiming a job that's still being worked.
     */
    renewLease(
        jobId: string,
        workerId: string,
        leaseSeconds: number,
    ): Promise<JobVO>;

    /**
     * Requeue every PROCESSING job held by a worker in `deadWorkerIds` —
     * status back to QUEUED, lock and lease cleared. Returns the count.
     */
    reclaimFromDeadWorkers(deadWorkerIds: string[]): Promise<number>;

    /**
     * The safety net: requeue any PROCESSING job whose `lease_expires_at` is
     * in the past, regardless of its worker's heartbeat status. Returns the
     * count. Runs alongside reclaimFromDeadWorkers — see JobRecoveryScheduler
     * for why both exist.
     */
    reclaimExpiredLeases(): Promise<number>;

    /**
     * Promote PENDING jobs whose `run_at` has arrived to QUEUED — claim only
     * ever looks at QUEUED, so this is what actually activates a delayed or
     * scheduled job. Returns the count promoted.
     */
    promotePendingJobs(): Promise<number>;

    /** List DEAD_LETTER jobs, most recently dead-lettered first. */
    listDeadLetter(
        input: ListDeadLetterJobsInput,
    ): Promise<ListDeadLetterJobsResult>;

    /**
     * Reset a DEAD_LETTER job back to QUEUED with attempts cleared to 0, for
     * a manual retry. Throws AppError.conflict if the job isn't DEAD_LETTER
     * (including if it doesn't exist).
     */
    retryDeadLetterJob(jobId: string): Promise<JobVO>;

    /**
     * Cancel a job. PENDING/QUEUED jobs move straight to CANCELLED — they
     * were never picked up, so this is unconditional. A PROCESSING job
     * can't be force-stopped (there's no way to interrupt a running
     * handler), so it's just flagged with cancelRequested for visibility;
     * it still runs to completion. Throws AppError.conflict for a job
     * that's already COMPLETED, DEAD_LETTER, or CANCELLED (including if it
     * doesn't exist).
     */
    cancel(jobId: string): Promise<JobVO>;

    /**
     * Count unprocessed backlog: jobs currently PENDING or QUEUED. Used to
     * enforce backpressure at submission time — PROCESSING isn't backlog
     * (already being worked), and terminal statuses (COMPLETED/
     * DEAD_LETTER/CANCELLED) aren't either.
     */
    countBacklog(): Promise<number>;
}
